### ISSUE TITLE
Set flannel subnet range when etcd and docker run on different hosts

### ISSUE THREAD

**Issue by jmcarp** [18F/kubernetes-release#24]
Currently, the flannel job in docker-boshrelease sets the flannel subnet range from a host that is running both docker and etcd. When using a separate etcd cluster, setting the flannel subnet range fails. Options:
- If https://github.com/cloudfoundry-community/docker-boshrelease/pull/71 is merged, update configuration
- If patch is not merged, add a job or errand to set subnet range before flannel starts

cc @cnelson

**Comment by cnelson** [comment]
@jmcarp I've added `flannel.ip-range` to stage and prod: 

https://ci.fr.cloud.gov/teams/main/pipelines/deploy-kubernetes/jobs/deploy-kubernetes-staging/builds/180

https://ci.fr.cloud.gov/teams/main/pipelines/deploy-kubernetes/jobs/deploy-kubernetes-production/builds/41

Can you verify/close this?

**Comment by jmcarp** [comment]
Verified, thanks for fixing.
